In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.eye(1,10,k=4)

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [5]:
np.where(np.arange(10)==4,1,0)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
np.arange(49, 9, -1)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [9]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
a = np.array([1,2,0,0,4,0], int)
a[a > 0]

array([1, 2, 4])

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
a = np.random.random(9).reshape(3,3)
a

array([[0.88106194, 0.62528405, 0.66950937],
       [0.21816763, 0.47269415, 0.57191075],
       [0.01215027, 0.36637323, 0.50373865]])

In [17]:
a[np.argmax(a)//3, np.argmax(a)%3], np.argmax(a)

(0.8810619374564386, 0)

In [19]:
np.mean(a, axis = 1), np.mean(a, axis = 0)

(array([0.72528512, 0.42092418, 0.29408738]),
 array([0.37045994, 0.48811714, 0.58171959]))