In [1]:
import numpy as np

In [2]:
# 11-1 길이가 10인 0-벡터를 만드세요.

vector = np.zeros(shape=(10,), dtype=np.int8)
vector.size

10

In [3]:
# 11-2 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인벡터를 만드세요
vector[4]=1
vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int8)

In [4]:
# 11-3 10 부터 49까지의 값을 가지는 벡터를 만드세요.

vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
# 11-4 위(3번) 벡터의 순서를 바꾸세요.
vector[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [6]:
# 11-5 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

vector = np.arange(9).reshape(3,3)
vector

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# 11-6 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를만드세요

vector = np.array([1, 2, 0, 0, 4, 0], float)
vector[vector > 0]

array([1., 2., 4.])

In [8]:
# 11-7
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# 11-8
a = np.random.uniform(0, 1, 9).reshape(3,3)
print(a)

[[0.22783146 0.96237792 0.78759822]
 [0.84508492 0.52257843 0.94587518]
 [0.2461877  0.75079875 0.78722483]]


In [10]:
# 11-9
np.min(a) 

0.2278314575792728

In [11]:
# 11-9
np.max(a)

0.9623779241330934

In [12]:
# 11-10
a.mean(axis=0)

array([0.43970136, 0.7452517 , 0.84023274])

In [13]:
# 11-10
a.mean(axis=1)

array([0.6592692 , 0.77117951, 0.5947371 ])